###### problem 1
**Find one or more each from Pandas, matplotlib, and scikit-learn.**
1. pandas.read_csv()
2. matplotlib.show()
3. sklearn.ensemble

###### problem 2
**Please explain what kind of method and instance variable were in the code used in the previous exercises.**

###### methods
1. pandas.loc()
2. pandas.iloc()
3. numpy.sum()
4. numpy.reshape()
5. numpy.ravel()

###### instance variable
1. ndarray.shape
2. ndarray.ndim
3. ndarray.dtype
4. ndarray.size
5. ndarray.data

In [1]:
# problem 3

import numpy as np

class ScratchStandardScaler():
    """
    標準化のためのクラス

    Attributes
    ----------
    mean_ : 次の形のndarray, shape(n_features,)
        平均
    var_ : 次の形のndarray, shape(n_features,)
        分散
    """
    def fit(self, X):
        """
        標準化のために平均と標準偏差を計算する。

        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            訓練データ
        """
        self.mean_ = np.mean(X, axis=0)
        self.var_ = np.var(X, axis=0)
        pass
    def transform(self, X):
        """
        fitで求めた値を使い標準化を行う。

        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            特徴量

        Returns
        ----------
        X_scaled : 次の形のndarray, shape (n_samples, n_features)
            標準化された特緒量
        """
        X_scaled = (X-self.mean_)/self.var_
        pass
        return X_scaled

In [2]:
from sklearn.datasets import load_iris
data = load_iris()
X = data.data[:10]
scratch_scaler = ScratchStandardScaler()
scratch_scaler.fit(X)
print("平均 : {}".format(scratch_scaler.mean_))
print("分散 : {}".format(scratch_scaler.var_))
X_std = scratch_scaler.transform(X)
print(X_std)

平均 : [4.86 3.31 1.45 0.22]
分散 : [0.0764 0.0849 0.0105 0.0056]
[[  3.14136126   2.23792697  -4.76190476  -3.57142857]
 [  0.52356021  -3.65135453  -4.76190476  -3.57142857]
 [ -2.09424084  -1.29564193 -14.28571429  -3.57142857]
 [ -3.40314136  -2.47349823   4.76190476  -3.57142857]
 [  1.83246073   3.41578327  -4.76190476  -3.57142857]
 [  7.06806283   6.94935218  23.80952381  32.14285714]
 [ -3.40314136   1.06007067  -4.76190476  14.28571429]
 [  1.83246073   1.06007067   4.76190476  -3.57142857]
 [ -6.02094241  -4.82921084  -4.76190476  -3.57142857]
 [  0.52356021  -2.47349823   4.76190476 -21.42857143]]


In [29]:
# problem 4

class ArthClass():
    """
    説明用の簡単なクラス

    Parameters
    ----------
    value : float or int
        初期値

    Attributes
    ----------
    value : float or int
        計算結果
    """
    def __init__(self, value):
        self.value = value
        if not isinstance(value, (int,float)):
            print("Please input only numbers")
        print("初期値{}が設定されました".format(self.value))
    def add(self, value2):
        """
        受け取った引数をself.valueに加える
        """
        self.value += value2
        
    def sub(self, value2):
        """
        substract the recevied argument with the self.value
        """
        self.value -= value2
    
    def mult(self, value2):
        """
        multiply the recevied argument with the self.value
        """
        self.value *= value2
    
    def div(self, value2):
        """
        divide the recevied argument with the self.value
        """
        self.value /= value2
        
example = ArthClass(5)
print("value : {}".format(example.value))
example.add(3)
print("addition value : {}".format(example.value))
example.sub(3)
print("subtraction value : {}".format(example.value))
example.mult(3)
print("multiplication value : {}".format(example.value))
example.div(9)
print("division value : {}".format(example.value))

初期値5が設定されました
value : 5
addition value : 8
subtraction value : 5
multiplication value : 15
division value : 1.6666666666666667
